import Link from 'next/link';
import { notFound } from 'next/navigation';
import { auth } from '../../../auth';
import { getSql } from '../../../lib/db';
import MarketplaceCard from '../../components/MarketplaceCard';

export const dynamic='force-dynamic';
export async function generateMetadata({params}){const{slug}=await params;return{title:`${decodeURIComponent(slug)} — Organização`}}
export default async function OrganizationPage({params}){
  const{slug}=await params;const sql=getSql();const organizations=await sql`SELECT id,slug,name,description FROM organizations WHERE lower(slug)=lower(${decodeURIComponent(slug)}) AND is_banned=false`;const org=organizations[0];if(!org)notFound();
  const [members,items,session]=await Promise.all([sql`SELECT u.id,u.username,u.display_name AS "displayName",u.avatar_url AS "avatarUrl",m.role FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.organization_id=${org.id} AND m.status='active' ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,lower(u.username)`,sql`SELECT i.id,i.type,i.name,i.author,i.description,i.version,i.cover_image_text AS "coverImageText",i.cover_image_url AS "coverImageUrl",i.downloads,o.slug AS "organizationSlug",o.name AS "organizationName" FROM items i JOIN organizations o ON o.id=i.organization_id WHERE i.organization_id=${org.id} AND i.status='approved' ORDER BY i.downloads DESC,i.created_at DESC`,auth()]);
  const current=members.find(m=>Number(m.id)===Number(session?.user?.id));const canManage=['owner','admin'].includes(current?.role);const downloads=items.reduce((sum,item)=>sum+Number(item.downloads||0),0);
  return <main className="page-container page-container-wide"><section className="profile-hero"><div className="profile-banner profile-banner-generated"><span>ORGANIZAÇÃO</span></div><div className="profile-identity"><div className="profile-avatar">{org.name.slice(0,2).toUpperCase()}</div><div><h1>{org.name}</h1><p>@{org.slug} · {org.description||'Organização da comunidade Ignis'}</p></div><div className="profile-actions">{canManage&&<Link className="button button-outline" href={`/organizations/${org.slug}/settings`}>Gerenciar</Link>}<Link className="button button-ghost" href={`/report?organization=${org.id}`}>⚑ Reportar</Link></div></div></section><section className="stats-grid"><div className="panel stat-card"><span>Membros</span><strong>{members.length}</strong></div><div className="panel stat-card"><span>Criações aprovadas</span><strong>{items.length}</strong></div><div className="panel stat-card"><span>Acessos</span><strong>{downloads.toLocaleString('pt-BR')}</strong></div></section><div className="org-grid"><section><div className="profile-section-heading"><div><p className="eyebrow">Catálogo</p><h2>Criações da organização</h2></div></div>{items.length?<div className="asset-grid">{items.map((item,index)=><MarketplaceCard key={item.id} item={item} index={index}/>)}</div>:<div className="empty-state"><strong>Nenhuma criação publicada.</strong></div>}</section><aside className="panel team-card"><h2>Equipe</h2>{members.map(member=><div className="team-member" key={member.id}>{member.avatarUrl?<img className="avatar" src={member.avatarUrl} alt=""/>:<span className="avatar avatar-fallback">◎</span>}<div><strong>{member.displayName||member.username}</strong><small>@{member.username} · {member.role}</small></div></div>)}</aside></div></main>
}
